# Generated by Django 2.2.1 on 2019-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_post_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
